//------------------------------------------------------------------------------
// <auto-generated>
//    這個程式碼是由範本產生。
//
//    對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//    如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace MSPMaterial.Model
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class bbdrytw1_msp_materialsEntities : DbContext
    {
        public bbdrytw1_msp_materialsEntities()
            : base("name=bbdrytw1_msp_materialsEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<errormessage> errormessage { get; set; }
        public DbSet<inputlist> inputlist { get; set; }
        public DbSet<loginlist> loginlist { get; set; }
        public DbSet<materials> materials { get; set; }
        public DbSet<outputlist> outputlist { get; set; }
        public DbSet<scrapped> scrapped { get; set; }
        public DbSet<user> user { get; set; }
        public DbSet<wiplist> wiplist { get; set; }
        public DbSet<typelist> typelist { get; set; }
    }
}
